# Generated by Django 3.1.12 on 2025-06-17 14:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID da Peça (1=Círculo, 2=Hexágono, 3=Quadrado)')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Peça')),
                ('tipo', models.CharField(choices=[('circulo', 'Círculo'), ('hexagono', 'Hexágono'), ('quadrado', 'Quadrado')], max_length=50, unique=True, verbose_name='Tipo de Forma')),
                ('qtd', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('color_hex', models.CharField(default='#CCCCCC', max_length=7, verbose_name='Cor Hexadecimal')),
            ],
            options={
                'verbose_name': 'Peça em Estoque',
                'verbose_name_plural': 'Peças em Estoque',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora do Pedido')),
                ('pecas', djongo.models.fields.JSONField(verbose_name='IDs das Peças nas Montagens')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('pausado', 'Pausado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='pendente', max_length=50, verbose_name='Status do Pedido')),
            ],
            options={
                'verbose_name': 'Pedido de Montagem',
                'verbose_name_plural': 'Pedidos de Montagem',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('peca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.peca', verbose_name='Peça')),
            ],
            options={
                'verbose_name': 'Estoque de Peça',
                'verbose_name_plural': 'Estoque de Peças',
            },
        ),
    ]
