# Generated by Django 3.1.12 on 2025-06-03 12:59

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('circulo', 'Círculo'), ('hexagono', 'Hexágono'), ('quadrado', 'Quadrado')], max_length=50)),
                ('qtd', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='estoque',
            old_name='quantidade',
            new_name='qtd',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='pedido',
            name='pecas',
            field=djongo.models.fields.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em Andamento'), ('entregue', 'Entregue')], max_length=50),
        ),
    ]
