# Generated by Django 3.1.12 on 2025-06-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID da Peça (1=Círculo, 3=Quadrado, 3=Hexágono)'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='tipo',
            field=models.CharField(choices=[('circulo', 'Círculo'), ('quadrado', 'Quadrado'), ('hexagono', 'Hexágono')], max_length=50, unique=True, verbose_name='Tipo de Forma'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[(3, 'Cancelado'), (2, 'Pendente'), (1, 'Em Andamento'), (0, 'Concluído')], default=2, verbose_name='Status do Pedido'),
        ),
    ]
