# Generated by Django 3.1.12 on 2025-06-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20250603_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
