# Generated by Django 3.1.12 on 2025-06-17 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20250605_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em Andamento'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], max_length=50),
        ),
    ]
