# Generated by Django 3.1.12 on 2025-06-17 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20250617_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora do Pedido'),
        ),
    ]
