# Generated by Django 3.1.12 on 2025-06-17 13:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20250617_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_type', models.CharField(choices=[('circulo', 'Círculo'), ('hexagono', 'Hexágono'), ('quadrado', 'Quadrado')], max_length=50, unique=True, verbose_name='Tipo de Forma')),
                ('low_stock_limit', models.IntegerField(default=2, verbose_name='Limite de Estoque Baixo')),
            ],
            options={
                'verbose_name': 'Limite de Estoque',
                'verbose_name_plural': 'Limites de Estoque',
            },
        ),
        migrations.AlterModelOptions(
            name='estoque',
            options={'verbose_name': 'Estoque de Peça', 'verbose_name_plural': 'Estoque de Peças'},
        ),
        migrations.AlterModelOptions(
            name='peca',
            options={'verbose_name': 'Peça Cadastrada', 'verbose_name_plural': 'Peças Cadastradas'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido de Montagem', 'verbose_name_plural': 'Pedidos de Montagem'},
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='id',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='qtd',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='tipo',
        ),
        migrations.AddField(
            model_name='estoque',
            name='peca',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.peca', verbose_name='Peça'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peca',
            name='color_hex',
            field=models.CharField(default='#CCCCCC', max_length=7, verbose_name='Cor Hexadecimal'),
        ),
        migrations.AddField(
            model_name='peca',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True, verbose_name='Nome da Peça'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peca',
            name='shape_type',
            field=models.CharField(choices=[('circulo', 'Círculo'), ('hexagono', 'Hexágono'), ('quadrado', 'Quadrado')], default=django.utils.timezone.now, max_length=50, verbose_name='Tipo de Forma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estoque',
            name='qtd',
            field=models.IntegerField(default=0, verbose_name='Quantidade em Estoque'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora do Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pecas',
            field=djongo.models.fields.JSONField(verbose_name='IDs das Peças nas Montagens'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('pausado', 'Pausado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='pendente', max_length=50, verbose_name='Status do Pedido'),
        ),
    ]
