# Generated by Django 3.1.12 on 2025-06-17 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20250617_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LimiteEstoque',
        ),
        migrations.AddField(
            model_name='estoque',
            name='tipo',
            field=models.CharField(choices=[('circulo', 'Círculo'), ('hexagono', 'Hexágono'), ('quadrado', 'Quadrado')], default=django.utils.timezone.now, max_length=50, verbose_name='Tipo de Forma (do Estoque)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peca',
            name='shape_type',
            field=models.CharField(choices=[('circulo', 'Círculo'), ('hexagono', 'Hexágono'), ('quadrado', 'Quadrado')], max_length=50, unique=True, verbose_name='Tipo de Forma'),
        ),
    ]
