# Generated by Django 3.1.12 on 2025-06-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20250617_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peca',
            old_name='shape_type',
            new_name='tipo',
        ),
    ]
