# Generated by Django 3.1.12 on 2025-06-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20250617_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peca',
            options={'verbose_name': 'Peça em Estoque', 'verbose_name_plural': 'Peças em Estoque'},
        ),
        migrations.AddField(
            model_name='peca',
            name='qtd',
            field=models.IntegerField(default=0, verbose_name='Quantidade em Estoque'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID da Peça (1=Círculo, 2=Hexágono, 3=Quadrado)'),
        ),
    ]
